version: '3.4'

services:
  server:
    image: wvxbs/a3-usabilidade-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
     - .env
    ports: 
     - ${API_PORT}:${API_PORT}
    depends_on:
      - database
    links:
      - database
    volumes:
      - .:/app

  database:
    image: 'mongo'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
