version: '3.4'

services:
  api:
    image: a3-usabilidade-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    volumes:
      - .:/api
